namespace Kart.Analytics.Domain.ValueObjects;

/// <summary>
/// Strongly-typed identifier for the <see cref="Entities.IngestedEvent"/> aggregate root
/// (ddd-model.md) — database-design.md `analytics_raw_events.event_id`. Publisher-assigned (the
/// original event's own id), not generated by this service — it is also the de-dup key that makes
/// a redelivered or replayed event overwrite its own row rather than insert a duplicate
/// (edge-cases.md "Replay Correctness").
/// </summary>
public readonly record struct EventId(Guid Value) : ITypedEntityId<EventId>
{
    public static EventId New() => new(Guid.NewGuid());

    public static EventId From(Guid value) => new(value);

    public override string ToString() => Value.ToString();
}
