// <auto-generated />
using System;
using System.Collections.Generic;
using Kart.Analytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kart.Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kart.Analytics.Domain.Entities.DeadLetteredEvent", b =>
                {
                    b.Property<Guid>("DlqId")
                        .HasColumnType("uuid")
                        .HasColumnName("dlq_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("DlqLandedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dlq_landed_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ReprocessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reprocessed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("DlqId");

                    b.HasIndex("DlqLandedAt")
                        .HasDatabaseName("idx_analytics_dlq_events_pending")
                        .HasFilter("reprocessed_at IS NULL");

                    b.ToTable("analytics_dlq_events", (string)null);
                });

            modelBuilder.Entity("Kart.Analytics.Domain.Entities.IngestedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("ContainsPii")
                        .HasColumnType("boolean")
                        .HasColumnName("contains_pii");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PiiRedactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pii_redacted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.ComplexProperty<Dictionary<string, object>>("Envelope", "Kart.Analytics.Domain.Entities.IngestedEvent.Envelope#EventEnvelope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("event_type");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at");

                            b1.Property<string>("PartitionKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("partition_key");

                            b1.Property<string>("PublisherService")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("publisher_service");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SchemaVersion", "Kart.Analytics.Domain.Entities.IngestedEvent.SchemaVersion#SchemaVersionPointer", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("SchemaId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("schema_id");

                            b1.Property<string>("VersionLabel")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("schema_version_label");
                        });

                    b.HasKey("EventId");

                    b.HasIndex("ContainsPii")
                        .HasDatabaseName("idx_analytics_raw_events_pii_pending")
                        .HasFilter("contains_pii = true AND pii_redacted_at IS NULL");

                    b.ToTable("analytics_raw_events", (string)null);
                });

            modelBuilder.Entity("Kart.Analytics.Domain.Entities.PiiRedactionRecord", b =>
                {
                    b.Property<Guid>("RedactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("redaction_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("RedactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redacted_at");

                    b.Property<int>("RowsRedacted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_redacted");

                    b.Property<Guid>("TriggeringEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggering_event_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("RedactionId");

                    b.HasIndex("UserId", "RedactedAt")
                        .HasDatabaseName("idx_analytics_pii_redactions_user");

                    b.ToTable("analytics_pii_redactions", (string)null);
                });

            modelBuilder.Entity("Kart.Analytics.Domain.Entities.ReconciliationRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date")
                        .HasColumnName("run_date");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("RunId");

                    b.HasIndex("RunDate")
                        .IsUnique()
                        .HasDatabaseName("uq_analytics_reconciliation_runs_run_date");

                    b.ToTable("analytics_reconciliation_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_analytics_reconciliation_runs_status", "status IN ('running', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("Kart.Analytics.Infrastructure.Persistence.AuditLogEntryRecord", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.HasKey("EntryId");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("idx_analytics_audit_log_entity");

                    b.ToTable("analytics_audit_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
